### ISSUE TITLE
Demo gives error (`"SharedArrayBuffer is not defined"`)

### ISSUE THREAD

**Issue by endegraaf** [ktock/vscode-container-wasm-gcc-example#1]
Followed the instructions as per readme, this is the result. Saw that the settings.json points to a dead link for the image (container.imageLocation). 

![image](https://github.com/ktock/vscode-container-wasm-gcc-example/assets/361011/cb0ef100-ccb5-48cc-be6a-5ff449dbe220)

**Comment by ktock** [comment]
Thanks for trying it! SharedArrayBuffer on github.dev seems to return errors sometimes. Could you reload the editor page sometimes (possible with clearing cache)?

Please see also: https://github.com/ktock/vscode-container-wasm-gcc-example?tab=readme-ov-file#sharedarraybuffer-is-not-defined-error-occurs-when-launching-the-container

**Comment by endegraaf** [comment]
After reload it seems to work.
